import BackButton from "@/components/back-button";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return <div className="w-screen h-screen flex items-center justify-center relative">
   <BackButton/>
    {children}
    </div>;
}
